### ISSUE TITLE
App crashes on incoming SMS

### ISSUE THREAD

**Issue by di72nn** [nerzhul/ownCloud-SMS-App#113]
### Steps to reproduce
Not sure about it. Probably: receive a new SMS when there are no messages.

### Expected behaviour
The app should not crash.

### Actual behaviour
The app crashes.

### Client configuration

**Android version:** 4.4.4 (CM11)

**ownCloud SMS app version:** 0.22.1 (from F-Droid)

### Logs

```
11-02 02:00:04.086 25816-25816/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: fr.unix_experience.owncloud_sms, PID: 25816
                                                   android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                       at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
                                                       at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                       at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
                                                       at android.database.CursorWrapper.getInt(CursorWrapper.java:102)
                                                       at fr.unix_experience.owncloud_sms.engine.SmsFetcher.handleProviderColumn(SmsFetcher.java:202)
                                                       at fr.unix_experience.owncloud_sms.engine.SmsFetcher.getLastMessage(SmsFetcher.java:112)
                                                       at fr.unix_experience.owncloud_sms.observers.SmsObserver.onChange(SmsObserver.java:63)
                                                       at android.database.ContentObserver.onChange(ContentObserver.java:129)
                                                       at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:180)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
                                                       at dalvik.system.NativeStart.main(Native Method)
```

I skipped some details from the issue template that seemed to be unrelated. I can provide this info if it really matters.

**Comment by nerzhul** [comment]
Thanks for the backtrace, will look at this now.

**Comment by nerzhul** [comment]
Hmmm this is very very strange. We are in the following loop:

```
for (int idx = 0; idx < c.getColumnCount(); idx++) {
```
This call works
```
String colName = c.getColumnName(idx);
```

but not this
```
entry.put(colName, (c.getInt(idx) > 0) ? "true" : "false");
```

**Comment by nerzhul** [comment]
I released 0.22.2 to renforce the strengthness of this code part. Please tell me if it works for you

**Comment by di72nn** [comment]
I'll test it as soon as F-Droid build it.

I believe `c.getColumnName(idx)` fetches column info and doesn't care about rows, but `c.getInt(idx)` tries to access the first row and fails if there are no rows present.

**Comment by nerzhul** [comment]
@di72nn this is possible and i fixed the problem that we have an empty cursor content with this release, i hope this will fix your problems

**Comment by di72nn** [comment]
Seems to be fine now.
Thank you for developing the app, BTW.

**Comment by nerzhul** [comment]
@di72nn thanks for the feedback and to lookup the code, the refactored code is now more secure :)
