### ISSUE TITLE
Circular redirect on latest Android version

### ISSUE THREAD

**Issue by Xefir** [nerzhul/ownCloud-SMS-App#127]
### Steps to reproduce
1. Add your Nextcloud instance
2. Synchronise
3. Get the error in notification center

### Expected behaviour
We should synchronise successfully without the "error #9: server set unhandled http return"

### Actual behaviour
The synchronisation leads to "error #9: server set unhandled http return" in the notification bar

### Server configuration

**Nextcloud version:** 
11.0.0

**PHP version:**
5.6.29

**HTTPd server:**
Nginx 1.6.2

**HTTPS:**
Yes

### Client configuration

**Android version:**
7.1.1

**Phone:**
Nexus 5X

**ownCloud SMS app version:**
Latest Play Store 0.23.2

### Logs

```
12-25 16:54:47.646 28450 28464 I fr.unix_experience.owncloud_sms.engine.OCHttpClient: Create GET https://xxx/index.php/apps/ocsms/get/apiversion?format=json
12-25 16:54:49.414 28450 28464 I OCSMSOwnCloudClient: HTTP Request done at try 1
12-25 16:54:49.416 28450 28464 I SmsSyncAdapter: Server API version: 1
12-25 16:54:49.416 28450 28464 I fr.unix_experience.owncloud_sms.engine.OCHttpClient: Create GET https://xxx/index.php/apps/ocsms/get/smsidlist?format=json
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: Unable to perform a connection to ownCloud instance
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: org.apache.commons.httpclient.CircularRedirectException: Circular redirect to 'https://xxx:443/index.php/apps/ocsms/get/smsidlist'
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpMethodDirector.processRedirectResponse(HttpMethodDirector.java:638)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:179)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCHttpClient.execute(OCHttpClient.java:98)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doHttpRequest(OCSMSOwnCloudClient.java:290)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doHttpRequest(OCSMSOwnCloudClient.java:267)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doPushRequestV1(OCSMSOwnCloudClient.java:111)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doPushRequest(OCSMSOwnCloudClient.java:102)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.sync_adapters.SmsSyncAdapter.onPerformSync(SmsSyncAdapter.java:54)
12-25 16:54:49.616 28450 28464 E OCSMSOwnCloudClient: 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
12-25 16:54:49.818 28450 28464 I OCSMSOwnCloudClient: HTTP Request done at try 2
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: Server set unhandled HTTP return code 400
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: Status code: 400. Response message: <html>
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: <head><title>400 Bad Request</title></head>
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: <body bgcolor="white">
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: <center><h1>400 Bad Request</h1></center>
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: <hr><center>nginx/1.6.2</center>
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: </body>
12-25 16:54:49.820 28450 28464 E OCSMSOwnCloudClient: </html>
12-25 16:54:49.836 28450 28464 W SmsSyncAdapter: onPerformSync: unhandled response
```

**Comment by nerzhul** [comment]
A circular redirect ? have you properly installed server backend ?

**Comment by Xefir** [comment]
Yes, I have NextCloud and the ocsms app installed via the App Store. Moreover, it stops working when I migrate to NextCloud and only your app have this behavior, so I don't think it was something to do with the server's configuration. Something I forgot to add : my NextCloud is behind a reverse proxy, but I don't think it would matter. Sorry for the delay and have an early happy new year :)

**Comment by nerzhul** [comment]
@Xefir i have 2 reverse proxies behind my nextcloud instance and i didn't notice this problem... did you see the ocsms app on the server ?

**Comment by Xefir** [comment]
Yep, the ocsms app in NextCloud works and show me the past SMS synced, I cancel mark as read messages when I click on them, so yeah, no problem and no error in the NextCloud logs

**Comment by Xefir** [comment]
I sent you an email. Thank you :)

**Comment by nerzhul** [comment]
This should be fixed in latest release i published yesterday to play store. I keep this issue opened as you give me credentials and i forget to test with it

**Comment by Xefir** [comment]
0.24.0 ?

There are some progress, we don't have the stacktrace anymore, but a 302 : 

```
01-20 09:42:05.381 15435 15871 I fr.unix_experience.owncloud_sms.engine.OCHttpClient: Create GET https://XXX/index.php/apps/ocsms/get/apiversion?format=json
01-20 09:42:06.798 15435 15871 I OCSMSOwnCloudClient: HTTP Request done at try 1
01-20 09:42:06.800 15435 15871 I SmsSyncAdapter: Server API version: 1
01-20 09:42:06.813 15435 15871 I fr.unix_experience.owncloud_sms.engine.OCHttpClient: Create GET https://XXX/index.php/apps/ocsms/get/smsidlist?format=json
01-20 09:42:08.071 15435 15871 I OCSMSOwnCloudClient: HTTP Request done at try 1
01-20 09:42:08.073 15435 15871 I OCSMSOwnCloudClient: No inbox Sms received from server (doPushRequest, get SMS list)
01-20 09:42:08.074 15435 15871 I OCSMSOwnCloudClient: No sent Sms received from server (doPushRequest, get SMS list)
01-20 09:42:08.074 15435 15871 I OCSMSOwnCloudClient: No drafts Sms received from server (doPushRequest, get SMS list)
01-20 09:42:08.074 15435 15871 I SmsDataProvider: queryNonExistingMessages !
01-20 09:42:08.101 15435 15871 I AndroidSmsFetcher: 107 messages read from content://sms/inbox
01-20 09:42:08.109 15435 15871 I SmsDataProvider: queryNonExistingMessages !
01-20 09:42:08.129 15435 15871 I AndroidSmsFetcher: 61 messages read from content://sms/sent
01-20 09:42:08.141 15435 15871 I SmsDataProvider: queryNonExistingMessages !
01-20 09:42:08.161  7786  7823 E SmsProvider: Invalid request: content://sms/drafts
01-20 09:42:08.414 15435 15871 I OCSMSOwnCloudClient: HTTP Request done at try 1
01-20 09:42:08.414 15435 15871 W HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
01-20 09:42:08.416 15435 15871 E OCSMSOwnCloudClient: Server set unhandled HTTP return code 302
01-20 09:42:08.416 15435 15871 E OCSMSOwnCloudClient: Status code: 302. Response message: 
01-20 09:42:08.445 15435 15871 W SmsSyncAdapter: onPerformSync: unhandled response
```

On the access logs : 

```
10.0.1.1 - Xefir [20/Jan/2017:09:39:29 +0100] "GET /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 200 13 "-" "Jakarta Commons-HttpClient/3.1"
10.0.1.1 - Xefir [20/Jan/2017:09:39:29 +0100] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 302 5 "-" "Jakarta Commons-HttpClient/3.1"
10.0.1.1 - Xefir [20/Jan/2017:09:39:30 +0100] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 200 14 "-" "Jakarta Commons-HttpClient/3.1"
10.0.1.1 - Xefir [20/Jan/2017:09:39:31 +0100] "POST /index.php/apps/ocsms/push?format=json HTTP/1.1" 302 5 "-" "Jakarta Commons-HttpClient/3.1"
```

Thank you :)

**Comment by nerzhul** [comment]
dup with #128 , i close this ticket to have only one discussion area
