### ISSUE TITLE
HTTP Error 400 Results in Error #9

### ISSUE THREAD

**Issue by MarcSN311** [nerzhul/ownCloud-SMS-App#128]
Hi,
im getting Error #9 on a regular basis. The server access log says:
`XXX.XXX.XXX.XXX - user [12/Jan/2017:05:16:49 -0600] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 400 166 "-" "Jakarta Commons-HttpClient/3.1"`

but there are no other entries in any other log file.

### Server configuration

**ownCloud version:** 
`Nextcloud 11.0.0 `

**PHP version:**
`PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)`

**HTTPd server:**
`nginx version: nginx/1.6.2`

### Client configuration

**Android version:**
`Android 6.0.1 Cyanogen Mod 13.0`

**Phone:**
`Samsung Galaxy S5 SM-G900F`

**ownCloud SMS app version:**
`0.23.2`

**Comment by nerzhul** [comment]
error 400 from server ? very strange, have you got some PHP logs ? can you run yourself the query using curl ?
curl -v --basic -u <user> https://cloud../index.php/apps/ocsms/get/smsidlist?format=json and give us the return ?

**Comment by MarcSN311** [comment]
The php logs don't report any errors! All log files I can find (Nextcloud log, php log, php-fpm log, nginx error log) are empty even though I get the error multiple times a Day. I don't get it always though...
I wrote a small script provoke the error using curl, I'll report the Output as soon as I get any!

**Comment by MarcSN311** [comment]
Hello,
I've been trying to reproduce this error using curl, but it doesn't occur. Is there a way to enable debug logging in either the server or the client?

**Comment by nerzhul** [comment]
okay, thanks for your return, you can have more informations by using logcat either on your phone or on your computing enabling developper mode

**Comment by MarcSN311** [comment]
Here is some logcat output. I don't know where this redirect comes from, i can't see it in the servers access log.
```
[ 01-18 20:18:49.911 19249:19274 E/OCSMSOwnCloudClient ]

Unable to perform a connection to ownCloud instance

org.apache.commons.httpclient.CircularRedirectException: Circular redirect to 'https://oc.marcsn.de:443/index.php/apps/files/'

	at org.apache.commons.httpclient.HttpMethodDirector.processRedirectResponse(HttpMethodDirector.java:638)

	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:179)

	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)

	at fr.unix_experience.owncloud_sms.engine.OCHttpClient.execute(OCHttpClient.java:98)

	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doHttpRequest(OCSMSOwnCloudClient.java:290)

	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.getServerAPIVersion(OCSMSOwnCloudClient.java:65)

	at fr.unix_experience.owncloud_sms.sync_adapters.SmsSyncAdapter.onPerformSync(SmsSyncAdapter.java:51)

	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)





[ 01-18 20:18:50.117 19249:19274 I/OCSMSOwnCloudClient ]

HTTP Request done at try 2



[ 01-18 20:18:50.119 19249:19274 E/OCSMSOwnCloudClient ]

Server set unhandled HTTP return code 400



[ 01-18 20:18:50.119 19249:19274 E/OCSMSOwnCloudClient ]

Status code: 400. Response message: <html>


<head><title>400 Bad Request</title></head>


<body bgcolor="white">


<center><h1>400 Bad Request</h1></center>


<hr><center>nginx</center>


</body>


</html>
```

**Comment by MarcSN311** [comment]
Here is the Logcat output:
```
01-18 20:48:50.292 19249 20631 I OCSMSOwnCloudClient: HTTP Request done at try 1

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: Unable to perform a connection to ownCloud instance

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: org.apache.commons.httpclient.CircularRedirectException: Circular redirect to 'https://oc.marcsn.de:443/index.php/apps/ocsms/get/smsidlist'

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpMethodDirector.processRedirectResponse(HttpMethodDirector.java:638)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:179)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCHttpClient.execute(OCHttpClient.java:98)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doHttpRequest(OCSMSOwnCloudClient.java:290)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doHttpRequest(OCSMSOwnCloudClient.java:267)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doPushRequestV1(OCSMSOwnCloudClient.java:111)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.engine.OCSMSOwnCloudClient.doPushRequest(OCSMSOwnCloudClient.java:102)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at fr.unix_experience.owncloud_sms.sync_adapters.SmsSyncAdapter.onPerformSync(SmsSyncAdapter.java:54)

01-18 20:48:50.431 19249 20631 E OCSMSOwnCloudClient: 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

01-18 20:48:50.623 19249 20631 I OCSMSOwnCloudClient: HTTP Request done at try 2

01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: Server set unhandled HTTP return code 400

01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: Status code: 400. Response message: <html>


01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: <head><title>400 Bad Request</title></head>


01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: <body bgcolor="white">


01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: <center><h1>400 Bad Request</h1></center>


01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: <hr><center>nginx</center>


01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: </body>


01-18 20:48:50.624 19249 20631 E OCSMSOwnCloudClient: </html>
```
and the corresponding access log output:
```
xxx.xxx.xxx.xxx - user [18/Jan/2017:13:49:51 -0600] "GET /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 200 13 "-" "Jakarta Commons-HttpClient/3.1"
xxx.xxx.xxx.xxx - user [18/Jan/2017:13:49:51 -0600] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 302 5 "-" "Jakarta Commons-HttpClient/3.1"
xxx.xxx.xxx.xxx - user [18/Jan/2017:13:49:51 -0600] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 400 166 "-" "Jakarta Commons-HttpClient/3.1"
```

**Comment by nerzhul** [comment]
I will release a new version with the previous fix & some more soon, i will look at the backlog to ensure stability, because some things changed, i hope you will test with newer version

**Comment by MarcSN311** [comment]
I'm receiving Error #9 on HTTP 302 now, but only when the App sends POST requests:
```
01-19 11:04:07.439   567   595 I OCSMSOwnCloudClient: HTTP Request done at try 1
01-19 11:04:09.213   567   595 I OCSMSOwnCloudClient: HTTP Request done at try 1
01-19 11:04:09.214   567   595 I OCSMSOwnCloudClient: No inbox Sms received from server (doPushRequest, get SMS list)
01-19 11:04:09.215   567   595 I OCSMSOwnCloudClient: No sent Sms received from server (doPushRequest, get SMS list)
01-19 11:04:09.215   567   595 I OCSMSOwnCloudClient: No drafts Sms received from server (doPushRequest, get SMS list)
01-19 11:04:12.212   567   595 I OCSMSOwnCloudClient: HTTP Request done at try 1
01-19 11:04:12.220   567   595 E OCSMSOwnCloudClient: Server set unhandled HTTP return code 302
01-19 11:04:12.220   567   595 E OCSMSOwnCloudClient: Status code: 302. Response message: 
```

```
xxx.xxx.xxx.xxx - user [19/Jan/2017:04:05:09 -0600] "GET /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 200 13 "-" "Jakarta Commons-HttpClient/3.1"
xxx.xxx.xxx.xxx - user [19/Jan/2017:04:05:09 -0600] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 302 5 "-" "Jakarta Commons-HttpClient/3.1"
xxx.xxx.xxx.xxx - user [19/Jan/2017:04:05:11 -0600] "GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 200 14 "-" "Jakarta Commons-HttpClient/3.1"
xxx.xxx.xxx.xxx - user [19/Jan/2017:04:05:14 -0600] "POST /index.php/apps/ocsms/push?format=json HTTP/1.1" 302 5 "-" "Jakarta Commons-HttpClient/3.1"
```

**Comment by nerzhul** [comment]
Okay noted 302 and your client doesn't follow it, right ?

**Comment by nerzhul** [comment]
note for me: http://www.baeldung.com/httpclient-redirect-on-http-post

**Comment by nerzhul** [comment]
Okay i understood a little bit the problem looking at owncloud client library, to know how their redirection mode works.
I pushed some fixed for redirection and tag 0.24.1 but i cannot release it yet, i will do it this evening. If you are able to test this release before i release it, this can be very good :)

**Comment by MarcSN311** [comment]
Can you send me a precompiled apk? i don't have an android compiler ready right now

**Comment by nerzhul** [comment]
i have tested the version on my phone since 2 days, i will publish apk on play store soon

**Comment by nerzhul** [comment]
Apk is in publication process in appstore
