### ISSUE TITLE
https not connection to host with other port than 443

### ISSUE THREAD

**Issue by efelon** [nerzhul/ownCloud-SMS-App#25]
Android version: 4.3.1 (CM 10.2.1.3)
    Phone: Samsung Galaxy S4 Mini
    ownCloud SMS app version: 0.16.1
    ownCloud Version: 7.0.4 (stable)
    ocsms Version: 1.4.1

I can successfully connect to my owncloud instance with this URL:
http://sub.myhost.org

It won't connect, asking if it is the correct server address with these URL(s) with self signed certificate:
https://sub.myhost.org:50666
https://sub.myhost.org:50666/

- Opening owncloud in the Android browser works with these two URLs.
- Certificate is already imported to Android
- Owncloud sync with calendar and contacts is up and running on the same phone

Greetings
Martin

**Comment by efelon** [comment]
# Logcat extract
(from PID 6080)

```
Line 3244: D/NoteListActivity( 6080): starting note synchonization
	Line 3245: D/NoteListActivity( 6080): writing modified notes to server
	Line 3246: D/NoteListActivity( 6080): deleting notes from server
	Line 3247: D/NoteListActivity( 6080): writing new notes to server
	Line 3248: D/NoteListActivity( 6080): getting notes from server
	Line 3259: W/System.err( 6080): java.io.IOException: No authentication challenges found
	Line 3260: W/System.err( 6080): 	at libcore.net.http.HttpURLConnectionImpl.getAuthorizationCredentials(HttpURLConnectionImpl.java:438)
	Line 3261: W/System.err( 6080): 	at libcore.net.http.HttpURLConnectionImpl.processAuthHeader(HttpURLConnectionImpl.java:418)
	Line 3262: W/System.err( 6080): 	at libcore.net.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:367)
	Line 3263: W/System.err( 6080): 	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:301)
	Line 3264: W/System.err( 6080): 	at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
	Line 3265: W/System.err( 6080): 	at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
	Line 3266: W/System.err( 6080): 	at org.aykit.owncloud_notes.NoteListActivity$DownloadNotesTask.doInBackground(NoteListActivity.java:1164)
	Line 3267: W/System.err( 6080): 	at org.aykit.owncloud_notes.NoteListActivity$DownloadNotesTask.doInBackground(NoteListActivity.java:1129)
	Line 3268: W/System.err( 6080): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	Line 3269: W/System.err( 6080): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	Line 3270: W/System.err( 6080): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	Line 3271: W/System.err( 6080): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	Line 3272: W/System.err( 6080): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	Line 3273: W/System.err( 6080): 	at java.lang.Thread.run(Thread.java:841)
	Line 3274: E/NoteListActivity( 6080): java.io.IOException: No authentication challenges found
	Line 3485: D/MySimpleCursorLoader( 6080): loading cursor
	Line 3497: I/ActivityManager(  773): START u0 {cmp=org.aykit.MyOwnNotes/org.aykit.owncloud_notes.SettingsActivity} from pid 6080
	Line 3513: D/SettingsActivity( 6080): saving settings-changes
	Line 3516: W/IInputConnectionWrapper( 6080): showStatusIcon on inactive InputConnection
	Line 4026: D/SettingsActivity( 6080): saving settings-changes
	Line 4027: I/ActivityManager(  773): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity} from pid 6080
	Line 4028: D/SettingsActivity( 6080): saving settings-changes
	Line 4030: D/MySimpleCursorLoader( 6080): loading cursor
```

**Comment by nerzhul** [comment]
Are you using google play application or F-Droid unofficial application ?

**Comment by efelon** [comment]
I'm using the application from F-Droid.

**Comment by nerzhul** [comment]
F-Droid doesn't use my modified ownCloud library because it's not packaged by me. Maybe ownCloud SMS must use it's own library to handle ownCloud instance, but it's not for now.

**Comment by nerzhul** [comment]
Please use Google Play Store app to avoid this issue.
